-- 基金管理系统初始化SQL脚本
-- 创建时间：2026-01-31
-- 作者：系统生成

-- ----------------------------
-- 0. 创建数据库和用户
-- ----------------------------

-- 创建数据库
CREATE DATABASE IF NOT EXISTS myfunds CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 创建用户并授权（如果使用root用户，可跳过此步骤）
-- CREATE USER IF NOT EXISTS 'myfunds'@'localhost' IDENTIFIED BY 'myfunds123';
-- GRANT ALL PRIVILEGES ON myfunds.* TO 'myfunds'@'localhost';
-- FLUSH PRIVILEGES;

-- 使用数据库
USE myfunds;

-- ----------------------------
-- 1. 用户表
-- ----------------------------
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `USERNAME` VARCHAR(50) NOT NULL COMMENT '用户名',
  `PASSWORD` VARCHAR(100) NOT NULL COMMENT '密码（加密存储）',
  `EMAIL` VARCHAR(100) COMMENT '电子邮箱',
  `PHONE` VARCHAR(20) COMMENT '手机号码',
  `NICKNAME` VARCHAR(50) COMMENT '昵称',
  `STATUS` VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE-活跃，INACTIVE-停用',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USERNAME` (`USERNAME`),
  UNIQUE KEY `UK_EMAIL` (`EMAIL`),
  UNIQUE KEY `UK_PHONE` (`PHONE`),
  INDEX `IDX_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- ----------------------------
-- 2. 基金表
-- ----------------------------
DROP TABLE IF EXISTS `FUND`;
CREATE TABLE `FUND` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '基金ID',
  `FUND_CODE` VARCHAR(20) NOT NULL COMMENT '基金代码',
  `FUND_NAME` VARCHAR(100) NOT NULL COMMENT '基金名称',
  `FUND_TYPE` VARCHAR(50) COMMENT '基金类型',
  `MANAGER` VARCHAR(50) COMMENT '基金经理',
  `ESTABLISH_DATE` DATETIME COMMENT '成立日期',
  `LATEST_NAV` DOUBLE COMMENT '最新净值',
  `DAY_GROWTH` DOUBLE COMMENT '日涨幅（%）',
  `WEEK_GROWTH` DOUBLE COMMENT '周涨幅（%）',
  `MONTH_GROWTH` DOUBLE COMMENT '月涨幅（%）',
  `QUARTER_GROWTH` DOUBLE COMMENT '季涨幅（%）',
  `YEAR_GROWTH` DOUBLE COMMENT '年涨幅（%）',
  `ESTIMATED_DAY_GROWTH` DOUBLE COMMENT '当日预估涨跌幅（%）',
  `ESTIMATED_NAV` DOUBLE COMMENT '当日预估净值',
  `ESTIMATED_PROFIT` DOUBLE COMMENT '当日预估收益（元）',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_FUND_CODE` (`FUND_CODE`),
  INDEX `IDX_FUND_TYPE` (`FUND_TYPE`),
  INDEX `IDX_MANAGER` (`MANAGER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='基金表';

-- ----------------------------
-- 3. 基金股票持仓表
-- ----------------------------
DROP TABLE IF EXISTS `FUND_STOCK`;
CREATE TABLE `FUND_STOCK` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '持仓ID',
  `FUND_ID` BIGINT NOT NULL COMMENT '基金ID',
  `STOCK_CODE` VARCHAR(20) NOT NULL COMMENT '股票代码',
  `STOCK_NAME` VARCHAR(100) NOT NULL COMMENT '股票名称',
  `HOLDING_RATIO` DOUBLE COMMENT '持仓比例（%）',
  `STOCK_PRICE` DOUBLE COMMENT '股票价格',
  `DAY_GROWTH` DOUBLE COMMENT '股票日涨幅（%）',
  `HOLDING_VALUE` DOUBLE COMMENT '持仓市值（元）',
  `REPORT_DATE` DATETIME COMMENT '报告日期',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `IDX_FUND_ID` (`FUND_ID`),
  INDEX `IDX_STOCK_CODE` (`STOCK_CODE`),
  CONSTRAINT `FK_FUND_STOCK_FUND_ID` FOREIGN KEY (`FUND_ID`) REFERENCES `FUND` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='基金股票持仓表';

-- ----------------------------
-- 4. 用户基金持仓表
-- ----------------------------
DROP TABLE IF EXISTS `USER_FUND`;
CREATE TABLE `USER_FUND` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '持仓ID',
  `USER_ID` BIGINT NOT NULL COMMENT '用户ID',
  `FUND_ID` BIGINT NOT NULL COMMENT '基金ID',
  `TOTAL_SHARES` DOUBLE COMMENT '持有总份额',
  `AVERAGE_COST` DOUBLE COMMENT '平均成本价',
  `TOTAL_COST` DOUBLE COMMENT '总成本',
  `CURRENT_VALUE` DOUBLE COMMENT '当前市值',
  `PROFIT_LOSS` DOUBLE COMMENT '盈亏金额',
  `PROFIT_LOSS_RATIO` DOUBLE COMMENT '盈亏率（%）',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_FUND` (`USER_ID`, `FUND_ID`),
  INDEX `IDX_USER_ID` (`USER_ID`),
  INDEX `IDX_FUND_ID` (`FUND_ID`),
  CONSTRAINT `FK_USER_FUND_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_USER_FUND_FUND_ID` FOREIGN KEY (`FUND_ID`) REFERENCES `FUND` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户基金持仓表';

-- ----------------------------
-- 5. 基金交易记录表
-- ----------------------------
DROP TABLE IF EXISTS `FUND_TRANSACTION`;
CREATE TABLE `FUND_TRANSACTION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '交易ID',
  `USER_ID` BIGINT NOT NULL COMMENT '用户ID',
  `FUND_ID` BIGINT NOT NULL COMMENT '基金ID',
  `TRANSACTION_TYPE` VARCHAR(20) NOT NULL COMMENT '交易类型：BUY-买入，SELL-卖出',
  `TRANSACTION_AMOUNT` DOUBLE NOT NULL COMMENT '交易金额（元）',
  `TRANSACTION_SHARES` DOUBLE NOT NULL COMMENT '交易份额',
  `TRANSACTION_PRICE` DOUBLE NOT NULL COMMENT '交易价格',
  `FEE` DOUBLE NOT NULL COMMENT '手续费（元）',
  `STATUS` VARCHAR(20) NOT NULL DEFAULT 'SUCCESS' COMMENT '交易状态：SUCCESS-成功，FAILED-失败，PENDING-处理中',
  `TRANSACTION_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '交易时间',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `IDX_USER_ID` (`USER_ID`),
  INDEX `IDX_FUND_ID` (`FUND_ID`),
  INDEX `IDX_TRANSACTION_TYPE` (`TRANSACTION_TYPE`),
  INDEX `IDX_STATUS` (`STATUS`),
  INDEX `IDX_TRANSACTION_TIME` (`TRANSACTION_TIME`),
  CONSTRAINT `FK_TRANSACTION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_TRANSACTION_FUND_ID` FOREIGN KEY (`FUND_ID`) REFERENCES `FUND` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='基金交易记录表';

-- ----------------------------
-- 6. 定投计划表
-- ----------------------------
DROP TABLE IF EXISTS `FIXED_INVESTMENT`;
CREATE TABLE `FIXED_INVESTMENT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '定投计划ID',
  `USER_ID` BIGINT NOT NULL COMMENT '用户ID',
  `FUND_ID` BIGINT NOT NULL COMMENT '基金ID',
  `AMOUNT` DOUBLE NOT NULL COMMENT '定投金额（元）',
  `FREQUENCY` VARCHAR(20) NOT NULL COMMENT '定投频率：DAILY-每日，WEEKLY-每周，MONTHLY-每月',
  `START_DATE` DATETIME NOT NULL COMMENT '开始日期',
  `NEXT_EXECUTION_DATE` DATETIME NOT NULL COMMENT '下次执行日期',
  `STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE-运行中，PAUSED-已暂停，STOPPED-已停止',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `IDX_USER_ID` (`USER_ID`),
  INDEX `IDX_FUND_ID` (`FUND_ID`),
  INDEX `IDX_STATUS` (`STATUS`),
  INDEX `IDX_NEXT_EXECUTION_DATE` (`NEXT_EXECUTION_DATE`),
  CONSTRAINT `FK_FIXED_INVESTMENT_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_FIXED_INVESTMENT_FUND_ID` FOREIGN KEY (`FUND_ID`) REFERENCES `FUND` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定投计划表';

-- ----------------------------
-- 7. 插入测试数据
-- ----------------------------
-- 插入测试用户
INSERT INTO `USER` (`USERNAME`, `PASSWORD`, `EMAIL`, `PHONE`, `NICKNAME`) VALUES 
('testuser', '123456', 'test@example.com', '13800138000', '测试用户');

-- 插入测试基金
INSERT INTO `FUND` (`FUND_CODE`, `FUND_NAME`, `FUND_TYPE`, `MANAGER`, `ESTABLISH_DATE`, `LATEST_NAV`, `DAY_GROWTH`) VALUES 
('000001', '华夏成长混合', '混合型', '张经理', '2001-12-18', 1.5678, 1.23);

-- 插入测试基金股票持仓
INSERT INTO `FUND_STOCK` (`FUND_ID`, `STOCK_CODE`, `STOCK_NAME`, `HOLDING_RATIO`, `STOCK_PRICE`, `DAY_GROWTH`, `HOLDING_VALUE`, `REPORT_DATE`) VALUES 
(1, '600000', '浦发银行', 8.5, 9.87, 0.56, 8500000.00, '2026-01-30'),
(1, '000001', '平安银行', 7.2, 15.67, -0.23, 7200000.00, '2026-01-30'),
(1, '601318', '中国平安', 6.8, 48.92, 1.89, 6800000.00, '2026-01-30');
